Feature/issue#3
kyutech-programming-club/lt-hub-backend pull request #27
Opened 2022-01-24 12:57 UTC by take-cantik

resolved #3 

頭ごちゃごちゃしてきた...
確認多めでお願いします.

2022-01-24 15:10 UTC, take-cantik commented
これでいいはず

2022-01-24 19:25 UTC, syu-kwsk requested changes
メソッドの細かいところまでは調べてないけど、たぶん違うだろうってところ

2022-01-24 19:25 UTC, syu-kwsk commented on backend/app/Models/Order.php
> +    }
これするならevent_idを持たないといけない（slackで言ったけど、たぶんもっといた方がいい気がする）

2022-01-24 19:25 UTC, syu-kwsk commented on backend/database/migrations/2022_01_22_145611_create_orders_table.php
> -            $table->unique(['event_id', 'talk_id', 'order']);
event_idはいると思う

2022-01-24 19:25 UTC, syu-kwsk commented on backend/app/Models/Event.php
> +    }
可能なのかわからんのやけど、ここってorderでソートしたものにできへんの？
下の`public function orders(): HasManyThroug`がそれを担ってる？

2022-01-25 00:53 UTC, take-cantik commented on backend/app/Http/Controllers/RoleController.php
> +}
Model作ったときに一緒にController作ったときの弊害ですね
Route一覧作るときについでにControllerのmethodまで考えようと思うのでそれまで保留でお願いします

2022-01-25 00:54 UTC, take-cantik commented on backend/app/Models/Event.php
> +        'location',
OMG

2022-01-25 00:54 UTC, take-cantik commented on backend/app/Models/User.php
> +    }
脳死ですねこれは

2022-01-25 01:03 UTC, take-cantik commented on backend/app/Models/Event.php
> +    }
それ用の書き方あるので、また別に書きます

2022-01-25 01:09 UTC, take-cantik commented on backend/database/migrations/2022_01_22_145611_create_orders_table.php
> -            $table->unique(['event_id', 'talk_id', 'order']);
slackにも書いた通りの理由でいらないと思ひました

2022-01-25 04:31 UTC, syu-kwsk approved these changes

2022-01-25 04:32 UTC, merged